apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-data-pv
  labels:
    type: mysql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/mysql/data
    server: servername
