---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql
  resources:
    requests:
      storage: 20Gi