---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dump-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mysqldump
  resources:
    requests:
      storage: 20Gi
