apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-dump-pv
  labels:
    type: mysql
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mysqldump
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/mysql/databasedump
    server: servername
